version: 0.2
#env:
#  variables:
#    LAMBDA_NAME: "idcrypt-backend"
#    BUCKET_NAME: "adrians-lambda-code-bucket"
phases:
  install:
    commands:
      - apt-get update
      # Install elastic search
      - apt-get install wget -y
      - apt-get install gnupg2 -y
      - wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.4.2-amd64.deb
      - wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.4.2-amd64.deb.sha512
      - sha512sum -c elasticsearch-7.4.2-amd64.deb.sha512
      - dpkg -i elasticsearch-7.4.2-amd64.deb
      # Install serverless and related plugins
      - npm install --silent --no-progress -g npm
      - npm install --silent --no-progress -g serverless@1.63.0
      - serverless plugin install -n serverless-python-requirements
      - npm install serverless-domain-manager@3.3.1 --save-dev
      - npm install serverless-offline@next --save-dev
      - npm install --save serverless-dynamodb-local
      - sls plugin install -n serverless-wsgi
  pre_build:
    commands:
      - pip install virtualenv
      - virtualenv env
      - . env/bin/activate
      - pip install -r requirements.txt
  build:
    commands:
      - sls dynamodb install
      - ./runTestSetup.sh
      - behave test-integration/features/ -f plain
      - ./runTestCleanup.sh
      - mkdir -p target/dev
      - mkdir target/qa
      - serverless package --package target/dev --stage dev -v -r eu-west-1
#      - serverless package --package target/qa --stage qa -v -r eu-west-1

#      - ISO_DATE=$(date +%Y-%m-%dT%H:%M:%S%z)
#      - TMP_DIR="dist-$ISO_DATE"
#      - mkdir $TMP_DIR
#      - cp *.py $TMP_DIR
#      - cp -rf app/ $TMP_DIR
#      - cp -rf env/lib/python3.8/site-packages/* $TMP_DIR
#      - cd $TMP_DIR; zip -r ../dist.zip *
#      - cd ..
#      -
#      - aws s3 cp dist.zip s3://$BUCKET_NAME/$LAMBDA_NAME/dist.zip
#      - aws lambda update-function-code --function-name $LAMBDA_NAME --s3-bucket $BUCKET_NAME --s3-key $LAMBDA_NAME/dist.zip --publish

artifacts:
  files:
    - target/**/*
    - serverless.yml
    - infra/*
    - deploy.sh
